version: '3.9'
services:
  readme.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "readme.notify.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "$MAIL_SMTP_PORT:8025"
      - "1083:8080"

  readme.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme.notify.rabbitmq
    ports:
      - '1088:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: $RABBIT_USER
      RABBITMQ_DEFAULT_PASS: $RABBIT_PASSWORD
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme.notify.mongodb:
    image: mongo
    container_name: readme.notify.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    ports:
      - $MONGO_PORT:27017
    volumes:
      - readme.notify.mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh $MONGO_HOST:$MONGO_PORT/$MONGO_DB --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.notify.mongodb.ui:
    image: mongo-express
    restart: always
    container_name: readme.notify.mongodb.ui
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USER:$MONGO_PASSWORD@$MONGO_HOST:$MONGO_PORT/$MONGO_DB

volumes:
  readme.notify.mongodb:
